### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by sschueller** [stemrollerapp/stemroller#1]
Please add support/docs for Linux (from what I can gather it is just some additional steps that need to be performed): https://news.ycombinator.com/item?id=32360616

**Comment by iffyloop** [comment]
Just commented on your pull request, but for anyone looking at issues: I'll try to address this within the next week once I have access to a Linux device again. Thanks for your patience.

**Comment by iffyloop** [comment]
Semi-related issue: #4

**Comment by iffyloop** [comment]
@sschueller how would you like to handle packaging/distribution. Snap? AppImage? Flatpak? Distro-specific package manager? Or do you think Linux users are fine just installing from source, as long as it's compatible with their OS?

**Comment by JuanM04** [comment]
I prefer Flatpak for GUIs, because I can install it from the "App Store". Otherwise, AppImage are good.

Distro-specific package managers require a lot more work to maintain, so I wouldn't recommend it for a multi-platform app

**Comment by iffyloop** [comment]
Good point; there's also Snapcraft for the Snap format though. Any particular reason you prefer Flatpak/Flathub?

**Comment by JuanM04** [comment]
I've only used Snap in Ubuntu. I don't know how often is used outside Ubuntu

**Comment by iffyloop** [comment]
Please see the issue mentioned above (#12). I'm hoping to merge in @fheft's PR #2 with some minor changes, and that should enable the app to run on Linux, but in the short-term it will be required for the user to manually install `ffmpeg` and `demucs` and run this project from source. I'll add instructions to the readme to simplify this as much as possible. Later on, in a future release, we'll figure out how to package it in a format that's as easy to use as `.exe` and `.app` are on Windows and macOS.

**Comment by iffyloop** [comment]
Update: please see https://github.com/stemrollerapp/stemroller/issues/29. Closing for now.

**Comment by monsrud** [comment]
This seems to work fine for running stemroller on Debian based Linux. I have processed some files and it works without any issues.

curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - && sudo apt-get install -y nodejs
git clone https://github.com/stemrollerapp/stemroller.git
cd stemroller
npm i -D
npm run build:svelte && npm run start
