### ISSUE TITLE
Can't start on archlinux

### ISSUE THREAD

**Issue by hoopengo** [stemrollerapp/stemroller#13]
It's give me error:
```
[electron] BEGIN processing video "NZp1ZSxgi4U" - "2017"
[electron] Downloading YouTube video "NZp1ZSxgi4U"; storing in "/tmp/StemRoller-pybH23/yt-audio"
[electron] Splitting video "NZp1ZSxgi4U"; 2 jobs using model "mdx_extra_q"...
[electron] treeKill process undefined
[electron] Trace: treeKill failed: Error: pid must be a number
[electron]     at killCurChildProcess (/home/hoopengo/code/git/stemroller/main-src/processQueue.cjs:60:15)
[electron]     at ChildProcess.<anonymous> (/home/hoopengo/code/git/stemroller/main-src/processQueue.cjs:77:7)
[electron]     at ChildProcess.emit (node:events:527:28)
[electron]     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
[electron]     at onErrorNT (node:internal/child_process:478:16)
[electron]     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[electron] Trace: Error: spawn demucs-cxfreeze ENOENT
[electron]     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
[electron]     at onErrorNT (node:internal/child_process:478:16)
[electron]     at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
[electron]   errno: -2,
[electron]   code: 'ENOENT',
[electron]   syscall: 'spawn demucs-cxfreeze',
[electron]   path: 'demucs-cxfreeze',
[electron]   spawnargs: [
[electron]     '/tmp/StemRoller-pybH23/yt-audio',
[electron]     '-n',
[electron]     'mdx_extra_q',
[electron]     '--repo',
[electron]     '/home/hoopengo/code/git/stemroller/anyos-extra-files/Models',
[electron]     '-j',
[electron]     2
[electron]   ]
[electron] }
[electron]     at processVideo (/home/hoopengo/code/git/stemroller/main-src/processQueue.cjs:217:13)
[electron]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by hoopengo** [comment]
i use node@18 and node@16,
anyway it doesn't work.

**Comment by iffyloop** [comment]
Are you sure you checked out the `develop` branch instead of the `main` one?

**Comment by hoopengo** [comment]
> Are you sure you checked out the `develop` branch instead of the `main` one? Please try that and post the output. Also, keep in mind that you need `ffmpeg` and `demucs` installed globally.

i think you must put info about installation required `ffmpeg` and `demucs` on linux and about run in the develop branch into readme file. 

And, it's infinity Processing.

**Comment by iffyloop** [comment]
Yes, good point. That info is actually already in the README but only in the one for the develop branch. Once I merge the changes into main it will no longer be an issue.

With regards to it being stuck on processing "infinitely," how long have you waited? Usually it takes around 15min on my machine, but on old PCs it sometimes takes over an hour.

**Comment by hoopengo** [comment]
> With regards to it being stuck on processing "infinitely," how long have you waited? Usually it takes around 15min on my machine, but on old PCs it sometimes takes over an hour.

I think, 5-6 hours maybe.

**Comment by iffyloop** [comment]
That's good to know. I've never seen it take that long so it probably is an error. I'll try to investigate the issue on my machine in the next few days and will let you know once it's fixed. Thank you for reporting this information!

**Comment by iffyloop** [comment]
Update: please see #29. Closing for now.
