### ISSUE TITLE
How can I use this lib on ios?

### ISSUE THREAD

**Issue by MuhammadAarfeen** [stemrollerapp/stemroller#20]
Is there any way to use it in swift

**Comment by iffyloop** [comment]
Unfortunately Demucs is not currently supported on iOS AFAIK (visit https://github.com/facebookresearch/demucs - this is the backend StemRoller uses to actually performs the song splitting). Maybe ask about this on the Demucs issue tracker, or look into Spleeter or other alternatives. Sorry I can't offer any further help, and please let me know if I'm mistaken.
