### ISSUE TITLE
Awesome SvelteKit

### ISSUE THREAD

**Issue by janosh** [stemrollerapp/stemroller#24]
Very cool project! Just a heads-up that I added StemRoller to https://awesome-sveltekit.netlify.app/stemroller in https://github.com/janosh/awesome-sveltekit/commit/942e227957164ab8b659ab503e980a1bd5d43c5d.

Let me know if any of the metadata needs to change. If not, feel free to close this issue.

**Comment by iffyloop** [comment]
Looks good, thanks for asking this project!
