### ISSUE TITLE
feature request: allow song uploads

### ISSUE THREAD

**Issue by mrmos** [stemrollerapp/stemroller#3]
hello - just throwing this in here. I expected to be able to load some of my own music into the app to be split

**Comment by mrmos** [comment]
marketing says "ANY SONG" but more like any song that we can return in our search

**Comment by iffyloop** [comment]
Yes - this is a great idea and has been planned since the first version of StemRoller but didn't make it into the release. Several people have been asking for this feature, so I'll try to make time to work on it in the next week. We'll use this issue to track progress and I'll write an update here in the next few days. Thanks for your suggestion!

**Comment by mindplay-dk** [comment]
"upload"? I don't understand... I see Python and a Models folder in the 1.4GB (!) unpacked application folder, so I'd assume this all runs locally, right? Not in the cloud or something?

Is it tied to YouTube? Or what is it even searching? Where's the music coming from?

Being able to search and download music from the web seems like it would be a a secondary feature - a nice extra. I would assume it's much simpler to load audio from a local file than search the web for videos and extracting the audio?

Seems odd. 🤷‍♂️

**Comment by dangom** [comment]
You can use demucs directly from the terminal. No need to go through stemroller for that.
```
pip install demucs
demucs song.wav
```

**Comment by iffyloop** [comment]
@mindplay-dk by "upload" we are actually referring to splitting a local file, as you anticipated would be most logical, not an actual upload to YouTube. And yes, you are correct that audio is being downloaded from YouTube first and then split locally on your device.
The reason I created StemRoller was to abstract away all the downloading and splitting steps, so anyone can just search a song and split it. It's basically just youtube-dl and Demucs bundled with a GUI.

@dangom thanks for mentioning that. For now, splitting manually with Demucs is the ideal solution until we get a local file GUI in StemRoller.

**Comment by alectrocute** [comment]
Made a PR for this: https://github.com/stemrollerapp/stemroller/pull/11

Open to suggestions, etc. It's definitely a "quick and easy" solution to *at least allow* this for now.

**Comment by iffyloop** [comment]
Exciting! Let's continue discussion in the PR for now...

**Comment by iffyloop** [comment]
Feature has been implemented in the `develop` branch! Will merge it into the next release! Thanks for your help, and if you want to test out the new implementation and provide feedback I'd be happy to hear it. Haven't tested on Mac yet so that'd be helpful if you get the chance.

**Comment by iffyloop** [comment]
Implemented in the latest release (1.1.0)! Closing.
