### ISSUE TITLE
Automate Builds

### ISSUE THREAD

**Issue by iffyloop** [stemrollerapp/stemroller#4]
Would like to look into using GitHub Actions or similar platform to automate builds for all three platforms (Windows, macOS, Linux). Will do some research at a later date, but if anyone has input/advice then please share it in this thread.

**Comment by krystalgamer** [comment]
Here's some suggestions:

* Create a new repo `steamroller-deps`, which would contain a GH action to automatically generate a neat zip for all supported OSes with `demucs-cxfreeze`, `ffpmpeg` and the models. For linux builds you can probably skip `ffmpeg` and install it through a packcage manager.
* The GH action running in this repo would simply download the latest release export and run `npm build`

**Comment by iffyloop** [comment]
Thanks so much @krystalgamer, looking forward to checking out your repo soon!

**Comment by iffyloop** [comment]
Implemented in the latest release (1.1.0)! Closing.
