### ISSUE TITLE
Request: Multiple Vocals split

### ISSUE THREAD

**Issue by vootox** [stemrollerapp/stemroller#43]
Diarization techniques (I guess) to identify and separate multiple vocals. A use-case: extracting multiple speakers or characters from a movie (audio track) which was my motivation for this request as a feature.

**Comment by iffyloop** [comment]
This would be a great feature to have. I haven't yet seen any open-source AI models that are reliably able to perform this task; do you know of any? (I haven't researched this in a long time...)

**Comment by vootox** [comment]
I'm new to this, but I wanted to at least have something to report before I replied.  I'm also not heavily into coding but I only just tried AssemblyAI (with free tokens). With some help from chatGPT, I managed to write a few lines of code to successfully export the audio segments from the characters/speakers of around ten x 40 min videos. I was personally really impressed with the results (from at least 8 out of the 10). Background noise was a critical factor that I'm sure would have boosted my results if I'd taken the time to do that part more carefully on the high-quality source than the low-quality copies (I had mistakenly switched somehow in my mode of operations).

I'm hoping to soon try pyannote-audio to do the same thing, but this time around I should prepare the audio more carefully.
Hope you can do some research as I'm certain this is an exciting time to include such functionality, for so many creative purposes.

**Comment by iffyloop** [comment]
Closing for now as this is not immediately relevant to the StemRoller project and have not heard any updates recently.
