### ISSUE TITLE
Integration as plugin for DAWs

### ISSUE THREAD

**Issue by CSumm** [stemrollerapp/stemroller#48]
First I want to say that this is a wonderful tool and does a great job separating tracks.

I'd like to know if a plugin for DAW integration would be in the works?  Looking forward to contributing to this project when I have some free time.

Thanks in advance!

**Comment by KewkLW** [comment]
Just an FYI if you wanted quick access to something, Serato Sampler integrated stem separation into it a little while back.

**Comment by iffyloop** [comment]
@CSumm great question! The Demucs model used by StemRoller was not designed for real-time inference, and even if it could run in real-time, would probably introduce a significant amount of latency. I can't work on this myself, as my current device does not have a GPU compatible with Demucs, so it uses very slow CPU inference (definitely not fast enough for real-time use). In theory, it should be possible though, as some people have gotten Spleeter (an older stem separation model) working in a VST plugin: https://github.com/diracdeltas/vstSpleeter - unfortunately this was not very stable when I tested it.

**Comment by iffyloop** [comment]
I'm closing this for now, since I can't work on it, and have several other old issue that I still need to address. However, if you or someone else are interested in working on this, feel free to comment here and we'll reopen it!
