### ISSUE TITLE
⌘+A does not work in the search bar

### ISSUE THREAD

**Issue by zmilonas** [stemrollerapp/stemroller#5]
**Steps to reproduce:**

1. Launch app
2. Type in a search term like 'asda'
3. Use a key combination of <kbd>⌘</kbd><kbd>A</kbd> while still having caret active in the search bar

**What happens?**

Nothing notable

**What is expected?**

The whole search bar text is highlited and selected.

**Environment**

Because of access only to macOS at the moment I was able to reproduce this only on the macOS build, in macOS Monterey (12.4). Version of the app is 1.0.0

**I cannot reproduce this in the development version - current main branch commit**

**Comment by iffyloop** [comment]
Hmm... that's really strange. Thanks for reporting the issue, I'll take a look at it once some other bugs have been fixed.

**Comment by alectrocute** [comment]
@iffyloop It's because `Menu.setApplicationMenu` isn't being executed with paste, copy, select, etc. options, thus preventing `Command + A` from being available inside the `BrowserWindow`.

**Comment by iffyloop** [comment]
Oops, yes, that probably explains why I thought it worked when testing in development (before disabling the app menu) and then it broke in production. Thanks! Should be an easy solution, will be fixed in next Mac build.

**Comment by alectrocute** [comment]
@iffyloop Made a PR: https://github.com/stemrollerapp/stemroller/pull/10

**Comment by iffyloop** [comment]
Great! Have been working on fixing Mac-related issues today so this was the perfect time for a PR :) Thanks so much!

**Comment by iffyloop** [comment]
Fixed in the latest release (1.1.0)! Closing.
