### ISSUE TITLE
View search result in web browser

### ISSUE THREAD

**Issue by tofflos** [stemrollerapp/stemroller#51]
Sometimes I want to make sure I have selected the right Youtube video. Could you add a "View in Web Browser" button for each search result similar to the "View in File Browser" button that is displayed for completed separations?

**Comment by iffyloop** [comment]
Would be an easy change from a technical perspective, but I'd rather avoid adding more buttons which could clutter things from a UX perspective (although this is only one change, eventually more feature requests like this will come in and I'd rather not set a precedent of just adding more elements next to the existing Split button). It definitely adds value, though, as it's annoying to split the wrong song, so I'll think about if there's a clean way to implement this, and if so it could be added in a future update.
