### ISSUE TITLE
Built-in stem player with mute/solo

### ISSUE THREAD

**Issue by carlxo** [stemrollerapp/stemroller#52]
This is such a fantastic tool, thank you so much for making it!

I mostly use it to separate the bass stem and use that to practice bass guitar (I hope to see guitar and piano stems coming with later version of Demucs!)

In my opinion, a great feature enhancement would be if there was a stem player built in, an instant way to listen to the separated tracks.

If this then had mute and solo buttons for all tracks this would make StemRoller a fantastic music practice tool. You'd be able to solo your instrument, to closely hear what the artist played, and then mute it and play along without the original stem.

**Comment by sc-moonlight** [comment]
I use Studio One DAW for this.  I load the original as one track, then each stem as their own tracks.  
Then I set the tempo for all the tracks to the song BPM.  
This way I can either isolate a single track, play mostly the single stem but a little of the others, or some combination. 
And with the BPM set, I can also slow it all down.  

I'm pretty sure you can do the same in Audacity, but I paid for Studio One years ago, so I use that.

**Comment by carlxo** [comment]
Yes, Ableton Live is my DAW of choice and I used that to do it before but found it cumbersome. I've now started using Stem Creator from Native Instruments (https://www.stems-music.com/stem-creator-tool/) to get it playing quickly and not having to load up or make a new project in Ableton for every song I want to play.

But making this a feature within the app would be a huge QoL-feature in my opinion, and make it a one-stop-shop for people with a similar use case to mine! Just a suggestion!

**Comment by iffyloop** [comment]
This is a good suggestion, and something I've thought about adding for a while, although that would likely be a new major release that would involve rewriting pretty much the entire app, so is not likely to happen anytime soon.

**Comment by YeonV** [comment]
![image](https://github.com/stemrollerapp/stemroller/assets/28861537/e22d17e5-fbb2-4026-8c84-e8a684d7dc68)

**Comment by YeonV** [comment]
![image](https://github.com/stemrollerapp/stemroller/assets/28861537/d64202bb-5819-4dc8-8579-252a277455e4)

**Comment by YeonV** [comment]
![image](https://github.com/stemrollerapp/stemroller/assets/28861537/6d52cb1f-0b13-4519-adfb-e3569cfbf5a6)
Playbutton onclick ->
```js
await shell.openExternal('stemplayer://' + videoPath)
```

**Comment by iffyloop** [comment]
Closing this issue for now, as I'm not currently planning to integrate a stem player into StemRoller, especially since YeonV has made this tool available for everyone to download. @YeonV I'm not quite ready to add that external shell link yet, would need to do some testing across platforms to make sure it's handled correctly when `stemplayer://` is not installed, although that should be trivial so maybe will be added soon. I will link everyone to your tool when I announce the next release on Discord though, DM me if I forget.
