### ISSUE TITLE
[Feature Request] Is it possible to turn this app into a web front end?

### ISSUE THREAD

**Issue by hero-intelligent** [stemrollerapp/stemroller#55]
Is it possible to modify the app so that it can become a web based front end? I've noticed that the app is based on electron. If that's really the case, I can easily deploy it onto a powerful remote home server. That will increase freedom of deployment.

**Comment by iffyloop** [comment]
This is currently outside the scope of StemRoller, but yes, most of the app logic is independent from Electron and could be easily extracted into a standalone app (e.g. with SvelteKit). If you end up building this as a fork, please feel free to mention it here and/or on the StemRoller Discord server, I'm sure there are several other people who would be interested in this feature.
