### ISSUE TITLE
[Feature Request] Add a setting to output resulting stems to the same folder as the input file

### ISSUE THREAD

**Issue by CyclopsDragon** [stemrollerapp/stemroller#56]
A lot of the work that I do that would be aided by StemRoller benefits from strict file organization, so it's a little annoying for me to have to move the output files around every single time I use it. Would it be possible to add a toggle to use the input file's directory instead of making a new folder in a designated output path?

**Comment by iffyloop** [comment]
Yes, that should be possible in a future update

**Comment by iffyloop** [comment]
Released in #59 - preferences page now has checkbox "When splitting local files, use input file directory"
