### ISSUE TITLE
Feature Request: Cancel processing

### ISSUE THREAD

**Issue by EstiaanJ** [stemrollerapp/stemroller#6]
The abillity to pause and cancel processing, and the abillity remove queued songs

**Comment by iffyloop** [comment]
Great idea! Will add this as soon as I can.

**Comment by iffyloop** [comment]
Implemented now in the `develop` branch, will merge in on the next release!

**Comment by iffyloop** [comment]
Implemented in the latest release (1.1.0)! Closing.
