### ISSUE TITLE
idea: possibility to select different stem separation methods

### ISSUE THREAD

**Issue by blaise-tk** [stemrollerapp/stemroller#61]
Since demucs in some cases, especially for vowel separation is a bit deficient, it would be nice to be able to select between different models, even to be able to combine them.

For example to extract and download with demucs and then clean with some echo model.

I love using StemRoller for its ease of use, keep up the good work <3

https://github.com/karaokenerds/python-audio-separator
https://github.com/Anjok07/ultimatevocalremovergui

**Comment by iffyloop** [comment]
I would like to add this, but unfortunately have not yet figured out a good way to simplify the amount of complexity involved here. To support multiple models, StemRoller would effectively become a package manager, installing and updating multiple different versions of Python, dependencies, and models, as each different separator has different requirements. At the moment, I don't have the time available to dedicate to this issue.

Thanks for your support, glad you are enjoying StemRoller! I too would like to support more audio separation models someday, but that would need to be a complete rewrite/different application.
