### ISSUE TITLE
Demucs v4

### ISSUE THREAD

**Issue by mindplay-dk** [stemrollerapp/stemroller#62]
Are you using Demucs v4?

Looks like they may have made some substantial improvements to the model.

I can't tell what you're using, but the model download URLs appear to be 2 years old? 🙂

**Comment by iffyloop** [comment]
@mindplay-dk as far as I understand, yes, this is the most recent v4 model. I'm using `htdemucs-ft` here: https://github.com/adefossez/demucs/tree/main/demucs/remote. Please re-open the issue and correct me if there is a more recent model checkpoint I haven't seen.

**Comment by mindplay-dk** [comment]
My mistake! Not sure what I was misreading that day. sorry about that. 😊
