### ISSUE TITLE
Stemroller quit working.

### ISSUE THREAD

**Issue by kimbo-love** [stemrollerapp/stemroller#65]
I love Stemroller! Unfortunately, it recently quit working. I am using Mac OS High Seirra. I also tried it on my Windows machine with the same results. I downloaded "demucs-cxfreeze-1.0.0-mac_sierra.zip", but I don't know how to use it. I really wish I could get it working again. Any help would be much appreciated. Much respect, —Kimbo

**Comment by iffyloop** [comment]
Which version of Windows are you using?

**Comment by kimbo-love** [comment]
Greetings— I am using Mac OS High Seirra. Would love to get Stemroller going again. Respect, —Kimbo

    On Sunday, June 16, 2024 at 04:13:34 PM MST, iffyloop ***@***.***> wrote:  
 
 


Which version of Windows are you using?

**Comment by iffyloop** [comment]
I think the latest versions of StemRoller are unfortunately not compatible with macOS High Sierra. But since you mentioned your also tested on a Windows machine and it didn't work there: what version of Windows (not macOS) were you using on the Windows device.

**Comment by kimbo-love** [comment]
Hi— My Windows system is 8.1. —Kimbo

    On Sunday, June 16, 2024 at 05:56:02 PM MST, iffyloop ***@***.***> wrote:  
 
 


I think the latest versions of StemRoller are unfortunately not compatible with macOS High Sierra. But since you mentioned your also tested on a Windows machine and it didn't work there: what version of Windows (not macOS) were you using on the Windows device.

**Comment by kimbo-love** [comment]
Is it possible to get earlier versions of Stemroller?

    On Sunday, June 16, 2024 at 05:56:02 PM MST, iffyloop ***@***.***> wrote:  
 
 


I think the latest versions of StemRoller are unfortunately not compatible with macOS High Sierra. But since you mentioned your also tested on a Windows machine and it didn't work there: what version of Windows (not macOS) were you using on the Windows device.

**Comment by rastacre** [comment]
I'm using the Win32 version of the app and I think there might be an issue on the Youtube side.

Steamroller constantly fails to download videos and I tried downloading some videos manually from some of the various YT downloader sites but I did not find any that would work. my best guess is something ads related... :(

**Comment by iffyloop** [comment]
@kimbo-love wow... sorry for such a late reply! Yes, all StemRoller versions are accessible at: https://github.com/stemrollerapp/stemroller/releases
@rastacre Should be fixed now after pulling #70 - closing the issue but let me know if this continues to happen.

**Comment by kimbo-love** [comment]
Greetings— I so thank you for all your help! For future reference, (in case someone else has a similar problem) I have found that Stemroller 2.0.3 works on Mac Os X High Sierra. Just wanted to pass this info back to you. Respect, —Kimbo

    On Thursday, July 11, 2024 at 09:20:03 PM MST, iffyloop ***@***.***> wrote:  
 
 


@kimbo-love wow... sorry for such a late reply! Yes, all StemRoller versions are accessible at: https://github.com/stemrollerapp/stemroller/releases
@rastacre Should be fixed now after pulling #70 - closing the issue but let me know if this continues to happen.
