### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by murattr03** [stemrollerapp/stemroller#68]
It does not extract any video I uploaded or selected from Youtube, it gives a "failed" error. It was a problem I had before, but not with every video. I selected the file it extracted before and it gave failed error again. How can we solve this problem?

![resim_2024-07-10_005820199](https://github.com/stemrollerapp/stemroller/assets/93780724/bea29f7a-e095-4c52-ad6f-9c99e84a140a)

**Comment by Zacharybinx34** [comment]
Same issue here.

**Comment by lebull** [comment]
Same

**Comment by lebull** [comment]
Looks like this is related to ytdl-core

https://github.com/distubejs/ytdl-core/issues/29 (No one has chimed in on this one yet)

And simply updating the package lands us on the only other existing issue, lol

https://github.com/distubejs/ytdl-core/issues/30

**Comment by lebull** [comment]
If yal are OK with building from source, I stood up a PR here that will at least show what changes need to be made to get it working for now.

https://github.com/stemrollerapp/stemroller/pull/70

**Comment by stoda985** [comment]
Same problem for every single file shows the same message

**Comment by iffyloop** [comment]
Closed, thanks to @lebull's PR! Reopen if anyone is still having issues. Haven't tested on Windows yet.

**Comment by ea2399** [comment]
Im having the issue that anytime i upload anything local to Stemroller it immediately fails to convert. The naming of the file does not matter either
