### ISSUE TITLE
Hardware Req?

### ISSUE THREAD

**Issue by Emirhan-K** [stemrollerapp/stemroller#78]
What are the hardware requirements to use this repo?

**Comment by iffyloop** [comment]
I'm not sure of specific hardware requirements, but from my experience, you'll probably need at least 12-16gb RAM/VRAM (you can add more virtual RAM by increasing the swapfile size, although this will be slower and arguably worse for SSD lifetime), and if you want it to run fast, you'll need a CUDA or Apple Silicon GPU.
