### ISSUE TITLE
Option to just upload an audio file manually, not depending on YouTube. 

### ISSUE THREAD

**Issue by bask209** [stemrollerapp/stemroller#79]
Hi! 

I was using an older version of the app, but I'm guessing YouTube added some protection to downloads. 

I used demucs to manually get my stems on manually downloaded files, but, I still think StemRoller is such a great app, I've shared it with many friends musicians. They won't know how to use the demucs model, or a terminal, or anything, but they love a simple beautiful interface, so I think that option to just input any audio file would be awesome! 

Just that, thanks for the awesome work, I'll keep sharing. 

(I don't have much experience with Javascript but, if this feature needs some hands to be developed, I guess I could hop in. )

**Comment by bask209** [comment]
I actually just noticed the link. lol. Sorry about this.

**Comment by iffyloop** [comment]
@bask209 No problem, thank you for your kind words, and glad you're enjoying StemRoller!
