### ISSUE TITLE
Crashes on macOS Sierra

### ISSUE THREAD

**Issue by iffyloop** [stemrollerapp/stemroller#9]
Many users seem to want to run StemRoller on macOS versions as old as Sierra (10.12), but splitting consistently fails on that platform. Not sure if it's possible to fix, but hopefully repacking `demucs-cxfreeze` should fix the issue.

**Comment by alectrocute** [comment]
Reading this ticket reminds me that I feel like this project would greatly benefit from some sort of crash/error reporting.

**Comment by iffyloop** [comment]
Yes, it most definitely would. Any ideas on how we should collect and store that data, or if it should be optional/manual? Crash reporting won't make it into the next release but I'd like to start looking into options. We could open a new issue for it.

**Comment by alectrocute** [comment]
In my opinion, I think a 3rd-party service like Sentry’s free plan would get the job done for the time being, it integrates into Electron very easily and yeah – We should definitely make crash reporting optional via the upcoming settings menu (mentioned in another issue).

**Comment by iffyloop** [comment]
I've uploaded a `mac_sierra` build of `demucs-cxfreeze` on its [releases page](https://github.com/stemrollerapp/demucs-cxfreeze/releases/tag/1.0.0). Bundling this with StemRoller in the future should fix any issues.

**Comment by iffyloop** [comment]
Fixed in the latest release (1.1.0)! Closing.

**Comment by kimbo-love** [comment]
How do I use "mac_sierra build of demucs-cxfreeze"?

**Comment by iffyloop** [comment]
@kimbo-love Sorry for the late reply. It would probably be best if you just use the [Demucs CLI](https://github.com/facebookresearch/demucs) through Python, since the `mac_sierra` build is a slightly outdated version of the same thing. You'll just need to install Python first, then install `demucs`.

**Comment by kimbo-love** [comment]
Thanks for the tip! I'll see what I can do. I'm pretty basic when it comes to system management. I do appreciate you getting back to me. Have a beautiful day, —Kimbo

    On Monday, July 8, 2024 at 12:45:51 PM MST, iffyloop ***@***.***> wrote:  
 
 


@kimbo-love Sorry for the late reply. It would probably be best if you just use the Demucs CLI through Python, since the mac_sierra build is a slightly outdated version of the same thing. You'll just need to install Python first, then install demucs.
